Rails migration<br> removed address and address to consultations model<br> 2020-02-26T07:34:47.045949+00:00 app[web.1]: D, [2020-02-26T07:34:47.045770 #4] DEBUG -- : [d3a9ca2a-8b61-48e1-a802-8eacd2451200]   [1m[36mAppointment Load (1.6ms)[0m  [1m[34mSELECT "appointments".* FROM "appointments" WHERE "appointments"."consultation_id" = $1[0m  [["consultation_id", 1]] 2020-02-26T07:34:47.057917+00:00 app[web.1]: D, [2020-02-26T07:34:47.057795 #4] DEBUG -- : [d3a9ca2a-8b61-48e1-a802-8eacd2451200]   [1m[36mClient Load (6.0ms)[0m  [1m[34mSELECT "clients".* FROM "clients"[0m 2020-02-26T07:34:47.064275+00:00 app[web.1]: D, [2020-02-26T07:34:47.064175 #4] DEBUG -- : [d3a9ca2a-8b61-48e1-a802-8eacd2451200]   [1m[36mReview Load (3.4ms)[0m  [1m[34mSELECT "reviews".* FROM "reviews" WHERE "reviews"."consultation_id" = $1[0m  [["consultation_id", 1]] 2020-02-26T07:34:47.073285+00:00 app[web.1]: I, [2020-02-26T07:34:47.073181 #4]  INFO -- : [d3a9ca2a-8b61-48e1-a802-8eacd2451200]   Rendering pages/dashboard.html.erb within layouts/application 2020-02-26T07:34:47.080966+00:00 app[web.1]: D, [2020-02-26T07:34:47.080842 #4] DEBUG -- : [d3a9ca2a-8b61-48e1-a802-8eacd2451200]   [1m[35m (3.5ms)[0m  [1m[34mSELECT COUNT(*) FROM "privatemessages" WHERE "privatemessages"."user_id" = $1[0m  [["user_id", 9]] 2020-02-26T07:34:47.085306+00:00 app[web.1]: I, [2020-02-26T07:34:47.085237 #4]  INFO -- : [d3a9ca2a-8b61-48e1-a802-8eacd2451200]   Rendered vendor/bundle/ruby/2.6.0/gems/simple_calendar-2.3.0/app/views/simple_calendar/_week_calendar.html.erb (3.2ms) 2020-02-26T07:34:47.096907+00:00 app[web.1]: D, [2020-02-26T07:34:47.096768 #4] DEBUG -- : [d3a9ca2a-8b61-48e1-a802-8eacd2451200]   [1m[35m (3.1ms)[0m  [1m[34mSELECT COUNT(*) FROM "appointments" WHERE "appointments"."user_id" = $1[0m  [["user_id", 9]] 2020-02-26T07:34:47.104014+00:00 app[web.1]: D, [2020-02-26T07:34:47.103872 #4] DEBUG -- : [d3a9ca2a-8b61-48e1-a802-8eacd2451200]   [1m[36mConsultation Load (5.5ms)[0m  [1m[34mSELECT  "consultations".* FROM "consultations" WHERE "consultations"."user_id" = $1 LIMIT $2[0m  [["user_id", 9], ["LIMIT", 3]] 2020-02-26T07:34:47.105312+00:00 app[web.1]: I, [2020-02-26T07:34:47.105232 #4]  INFO -- : [d3a9ca2a-8b61-48e1-a802-8eacd2451200]   Rendered consultations/_show_min_products.html.erb (0.5ms) 2020-02-26T07:34:47.189568+00:00 app[web.1]: I, [2020-02-26T07:34:47.189428 #4]  INFO -- : [d3a9ca2a-8b61-48e1-a802-8eacd2451200]   Rendered consultations/_new_consultation_class_form.html.erb (83.5ms) 2020-02-26T07:34:47.210486+00:00 app[web.1]: I, [2020-02-26T07:34:47.210363 #4]  INFO -- : [d3a9ca2a-8b61-48e1-a802-8eacd2451200]   Rendered pages/dashboard.html.erb within layouts/application (135.7ms) 2020-02-26T07:34:47.213338+00:00 app[web.1]: I, [2020-02-26T07:34:47.213254 #4]  INFO -- : [d3a9ca2a-8b61-48e1-a802-8eacd2451200] Completed 500 Internal Server Error in 193ms (ActiveRecord: 30.5ms) 2020-02-26T07:34:47.215161+00:00 app[web.1]: F, [2020-02-26T07:34:47.215003 #4] FATAL -- : [d3a9ca2a-8b61-48e1-a802-8eacd2451200] 2020-02-26T07:34:47.221026+00:00 app[web.1]: F, [2020-02-26T07:34:47.220828 #4] FATAL -- : [d3a9ca2a-8b61-48e1-a802-8eacd2451200] ActionView::Template::Error (undefined method `address' for #<Consultation:0x000000000300ea80>): 2020-02-26T07:34:47.221469+00:00 app[web.1]: F, [2020-02-26T07:34:47.221375 #4] FATAL -- : [d3a9ca2a-8b61-48e1-a802-8eacd2451200]     23:       <%= f.input :consult_type, label: false, collection: ["camp", "conversation", "education",  "exam-prep", "group / club", "hobby", "interview prep","phone-only", "speech-prep", "trade / industry", "translation", "other"], prompt: "-select type-" %> 2020-02-26T07:34:47.221470+00:00 app[web.1]: [d3a9ca2a-8b61-48e1-a802-8eacd2451200]     24:         <h6> location <span class="red-text">&#42;</span></h6> 2020-02-26T07:34:47.221471+00:00 app[web.1]: [d3a9ca2a-8b61-48e1-a802-8eacd2451200]     25:         <%= f.input :consult_city, label: false, placeholder: "city"%> 2020-02-26T07:34:47.221471+00:00 app[web.1]: [d3a9ca2a-8b61-48e1-a802-8eacd2451200]     26:         <%= f.input :address, label: false, placeholder: "address" %> 2020-02-26T07:34:47.221472+00:00 app[web.1]: [d3a9ca2a-8b61-48e1-a802-8eacd2451200]     27:       <h6> term <span class="red-text">&#42;</span></h6> 2020-02-26T07:34:47.221473+00:00 app[web.1]: [d3a9ca2a-8b61-48e1-a802-8eacd2451200]     28:       <%= f.input :consult_period, label: false, default: ["hourly"], collection: ["hourly", "single-class", "one-week", "one-month", "3 month term"]%> 2020-02-26T07:34:47.221473+00:00 app[web.1]: [d3a9ca2a-8b61-48e1-a802-8eacd2451200]     29:       <div> 2020-02-26T07:34:47.221581+00:00 app[web.1]: F, [2020-02-26T07:34:47.221517 #4] FATAL -- : [d3a9ca2a-8b61-48e1-a802-8eacd2451200] 2020-02-26T07:34:47.221739+00:00 app[web.1]: F, [2020-02-26T07:34:47.221631 #4] FATAL -- : [d3a9ca2a-8b61-48e1-a802-8eacd2451200] app/views/consultations/_new_consultation_class_form.html.erb:26:in `block in _app_views_consultations__new_consultation_class_form_html_erb__294416925149449547_30473340' 2020-02-26T07:34:47.221740+00:00 app[web.1]: [d3a9ca2a-8b61-48e1-a802-8eacd2451200] app/views/consultations/_new_consultation_class_form.html.erb:3:in `_app_views_consultations__new_consultation_class_form_html_erb__294416925149449547_30473340' 2020-02-26T07:34:47.221741+00:00 app[web.1]: [d3a9ca2a-8b61-48e1-a802-8eacd2451200] app/views/pages/dashboard.html.erb:165:in `_app_views_pages_dashboard_html_erb___1343124555907595423_28718340' 2020-02-26T07:34:47.223352+00:00 heroku[router]: at=info method=GET path="/dashboard" host=eslsearch.herokuapp.com request_id=d3a9ca2a-8b61-48e1-a802-8eacd2451200 fwd="125.142.66.134" dyno=web.1 connect=0ms service=225ms status=500 bytes=1827 protocol=https 2020-02-26T07:35:00.948129+00:00 heroku[router]: at=info method=GET path="/consultations" host=eslsearch.herokuapp.com request_id=7a511482-d524-43d6-b785-779dfe472f04 fwd="125.142.66.134" dyno=web.1 connect=0ms service=30ms status=200 bytes=8903 protocol=https 2020-02-26T07:35:00.922099+00:00 app[web.1]: I, [2020-02-26T07:35:00.921954 #4]  INFO -- : [7a511482-d524-43d6-b785-779dfe472f04] Started GET "/consultations" for 125.142.66.134 at 2020-02-26 07:35:00 +0000 2020-02-26T07:35:00.923078+00:00 app[web.1]: I, [2020-02-26T07:35:00.923007 #4]  INFO -- : [7a511482-d524-43d6-b785-779dfe472f04] Processing by ConsultationsController#index as HTML 2020-02-26T07:35:00.926950+00:00 app[web.1]: D, [2020-02-26T07:35:00.926872 #4] DEBUG -- : [7a511482-d524-43d6-b785-779dfe472f04]   [1m[36mUser Load (1.2ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 9], ["LIMIT", 1]] 2020-02-26T07:35:00.928762+00:00 app[web.1]: I, [2020-02-26T07:35:00.928675 #4]  INFO -- : [7a511482-d524-43d6-b785-779dfe472f04]   Rendering consultations/index.html.erb within layouts/application 2020-02-26T07:35:00.931096+00:00 app[web.1]: D, [2020-02-26T07:35:00.931008 #4] DEBUG -- : [7a511482-d524-43d6-b785-779dfe472f04]   [1m[36mConsultation Load (1.0ms)[0m  [1m[34mSELECT  "consultations".* FROM "consultations" LIMIT $1 OFFSET $2[0m  [["LIMIT", 8], ["OFFSET", 0]] 2020-02-26T07:35:00.933947+00:00 app[web.1]: D, [2020-02-26T07:35:00.933860 #4] DEBUG -- : [7a511482-d524-43d6-b785-779dfe472f04]   [1m[36mUser Load (1.0ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 9], ["LIMIT", 1]] 2020-02-26T07:35:00.937591+00:00 app[web.1]: D, [2020-02-26T07:35:00.937514 #4] DEBUG -- : [7a511482-d524-43d6-b785-779dfe472f04]   [1m[36mReview Load (0.9ms)[0m  [1m[34mSELECT "reviews".* FROM "reviews" WHERE "reviews"."consultation_id" = $1[0m  [["consultation_id", 1]] 2020-02-26T07:35:00.938712+00:00 app[web.1]: I, [2020-02-26T07:35:00.938646 #4]  INFO -- : [7a511482-d524-43d6-b785-779dfe472f04]   Rendered consultations/_index.html.erb (7.0ms) 2020-02-26T07:35:00.938922+00:00 app[web.1]: I, [2020-02-26T07:35:00.938858 #4]  INFO -- : [7a511482-d524-43d6-b785-779dfe472f04]   Rendered consultations/index.html.erb within layouts/application (10.0ms) 2020-02-26T07:35:00.941250+00:00 app[web.1]: I, [2020-02-26T07:35:00.941167 #4]  INFO -- : [7a511482-d524-43d6-b785-779dfe472f04]   Rendered shared/_navbar.html.erb (1.5ms) 2020-02-26T07:35:00.941563+00:00 app[web.1]: I, [2020-02-26T07:35:00.941499 #4]  INFO -- : [7a511482-d524-43d6-b785-779dfe472f04]   Rendered shared/_flashes.html.erb (0.1ms) 2020-02-26T07:35:00.941844+00:00 app[web.1]: I, [2020-02-26T07:35:00.941782 #4]  INFO -- : [7a511482-d524-43d6-b785-779dfe472f04]   Rendered shared/_footer.html.erb (0.0ms) 2020-02-26T07:35:00.942629+00:00 app[web.1]: I, [2020-02-26T07:35:00.942557 #4]  INFO -- : [7a511482-d524-43d6-b785-779dfe472f04] Completed 200 OK in 19ms (Views: 11.3ms | ActiveRecord: 4.1ms) 2020-02-26T07:35:01.300400+00:00 app[web.1]: I, [2020-02-26T07:35:01.299870 #4]  INFO -- : [636869e1-8461-48e3-8fc1-77b800b75146] Started GET "/images/logo.png" for 125.142.66.134 at 2020-02-26 07:35:01 +0000 2020-02-26T07:35:01.308173+00:00 app[web.1]: F, [2020-02-26T07:35:01.308042 #4] FATAL -- : [636869e1-8461-48e3-8fc1-77b800b75146] 2020-02-26T07:35:01.308778+00:00 app[web.1]: F, [2020-02-26T07:35:01.308704 #4] FATAL -- : [636869e1-8461-48e3-8fc1-77b800b75146] ActionController::RoutingError (No route matches [GET] "/images/logo.png"): 2020-02-26T07:35:01.309158+00:00 app[web.1]: F, [2020-02-26T07:35:01.309089 #4] FATAL -- : [636869e1-8461-48e3-8fc1-77b800b75146] 2020-02-26T07:35:01.309307+00:00 app[web.1]: F, [2020-02-26T07:35:01.309224 #4] FATAL -- : [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call' 2020-02-26T07:35:01.309309+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call' 2020-02-26T07:35:01.309309+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/railties-5.0.6/lib/rails/rack/logger.rb:36:in `call_app' 2020-02-26T07:35:01.309312+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/railties-5.0.6/lib/rails/rack/logger.rb:24:in `block in call' 2020-02-26T07:35:01.309313+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.6/lib/active_support/tagged_logging.rb:69:in `block in tagged' 2020-02-26T07:35:01.309313+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.6/lib/active_support/tagged_logging.rb:26:in `tagged' 2020-02-26T07:35:01.309314+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.6/lib/active_support/tagged_logging.rb:69:in `tagged' 2020-02-26T07:35:01.309314+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/railties-5.0.6/lib/rails/rack/logger.rb:24:in `call' 2020-02-26T07:35:01.309314+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/request_id.rb:24:in `call' 2020-02-26T07:35:01.309315+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/method_override.rb:24:in `call' 2020-02-26T07:35:01.309315+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call' 2020-02-26T07:35:01.309316+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/activesupport-5.0.6/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call' 2020-02-26T07:35:01.309316+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/executor.rb:12:in `call' 2020-02-26T07:35:01.309317+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/actionpack-5.0.6/lib/action_dispatch/middleware/static.rb:136:in `call' 2020-02-26T07:35:01.309317+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call' 2020-02-26T07:35:01.309317+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/railties-5.0.6/lib/rails/engine.rb:522:in `call' 2020-02-26T07:35:01.309334+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/puma-3.11.0/lib/puma/configuration.rb:225:in `call' 2020-02-26T07:35:01.309335+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/puma-3.11.0/lib/puma/server.rb:624:in `handle_request' 2020-02-26T07:35:01.309335+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/puma-3.11.0/lib/puma/server.rb:438:in `process_client' 2020-02-26T07:35:01.309335+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/puma-3.11.0/lib/puma/server.rb:302:in `block in run' 2020-02-26T07:35:01.309336+00:00 app[web.1]: [636869e1-8461-48e3-8fc1-77b800b75146] vendor/bundle/ruby/2.6.0/gems/puma-3.11.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread' 2020-02-26T07:35:01.312172+00:00 heroku[router]: at=info method=GET path="/images/logo.png" host=eslsearch.herokuapp.com request_id=636869e1-8461-48e3-8fc1-77b800b75146 fwd="125.142.66.134" dyno=web.1 connect=0ms service=14ms status=404 bytes=1902 protocol=https 2020-02-26T07:35:04.844020+00:00 app[web.1]: I, [2020-02-26T07:35:04.843894 #4]  INFO -- : [0a72a98b-c5dc-4bac-a68b-420e4a3b6212] Started GET "/consultations/1" for 125.142.66.134 at 2020-02-26 07:35:04 +0000 2020-02-26T07:35:04.844937+00:00 app[web.1]: I, [2020-02-26T07:35:04.844868 #4]  INFO -- : [0a72a98b-c5dc-4bac-a68b-420e4a3b6212] Processing by ConsultationsController#show as HTML 2020-02-26T07:35:04.845010+00:00 app[web.1]: I, [2020-02-26T07:35:04.844950 #4]  INFO -- : [0a72a98b-c5dc-4bac-a68b-420e4a3b6212]   Parameters: {"id"=>"1"} 2020-02-26T07:35:04.847848+00:00 app[web.1]: D, [2020-02-26T07:35:04.847772 #4] DEBUG -- : [0a72a98b-c5dc-4bac-a68b-420e4a3b6212]   [1m[36mConsultation Load (0.8ms)[0m  [1m[34mSELECT  "consultations".* FROM "consultations" WHERE "consultations"."id" = $1 LIMIT $2[0m  [["id", 1], ["LIMIT", 1]] 2020-02-26T07:35:04.850139+00:00 app[web.1]: D, [2020-02-26T07:35:04.850032 #4] DEBUG -- : [0a72a98b-c5dc-4bac-a68b-420e4a3b6212]   [1m[36mUser Load (1.3ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 9], ["LIMIT", 1]] 2020-02-26T07:35:04.853601+00:00 app[web.1]: D, [2020-02-26T07:35:04.853531 #4] DEBUG -- : [0a72a98b-c5dc-4bac-a68b-420e4a3b6212]   [1m[36mLesson Load (1.0ms)[0m  [1m[34mSELECT "lessons".* FROM "lessons" WHERE "lessons"."consultation_id" = $1[0m  [["consultation_id", 1]] 2020-02-26T07:35:04.854319+00:00 app[web.1]: D, [2020-02-26T07:35:04.854255 #4] DEBUG -- : [0a72a98b-c5dc-4bac-a68b-420e4a3b6212]   [1m[36mCACHE (0.0ms)[0m  [1m[34mSELECT "lessons".* FROM "lessons" WHERE "lessons"."consultation_id" = $1[0m  [["consultation_id", 1]] 2020-02-26T07:35:04.856113+00:00 app[web.1]: D, [2020-02-26T07:35:04.856006 #4] DEBUG -- : [0a72a98b-c5dc-4bac-a68b-420e4a3b6212]   [1m[36mReview Load (0.9ms)[0m  [1m[34mSELECT "reviews".* FROM "reviews" WHERE "reviews"."consultation_id" = $1[0m  [["consultation_id", 1]] 2020-02-26T07:35:04.857679+00:00 app[web.1]: I, [2020-02-26T07:35:04.857606 #4]  INFO -- : [0a72a98b-c5dc-4bac-a68b-420e4a3b6212]   Rendering consultations/show.html.erb within layouts/application 2020-02-26T07:35:04.860382+00:00 app[web.1]: D, [2020-02-26T07:35:04.860311 #4] DEBUG -- : [0a72a98b-c5dc-4bac-a68b-420e4a3b6212]   [1m[36mUser Load (1.1ms)[0m  [1m[34mSELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 9], ["LIMIT", 1]] 2020-02-26T07:35:04.876571+00:00 app[web.1]: I, [2020-02-26T07:35:04.876464 #4]  INFO -- : [0a72a98b-c5dc-4bac-a68b-420e4a3b6212]   Rendered consultations/_details_consultation_show.html.erb (15.0ms) 2020-02-26T07:35:04.876689+00:00 app[web.1]: I, [2020-02-26T07:35:04.876627 #4]  INFO -- : [0a72a98b-c5dc-4bac-a68b-420e4a3b6212]   Rendered consultations/show.html.erb within layouts/application (18.6ms) 2020-02-26T07:35:04.876937+00:00 app[web.1]: I, [2020-02-26T07:35:04.876868 #4]  INFO -- : [0a72a98b-c5dc-4bac-a68b-420e4a3b6212] Completed 500 Internal Server Error in 32ms (ActiveRecord: 5.1ms) 2020-02-26T07:35:04.877611+00:00 app[web.1]: F, [2020-02-26T07:35:04.877545 #4] FATAL -- : [0a72a98b-c5dc-4bac-a68b-420e4a3b6212] 2020-02-26T07:35:04.877678+00:00 app[web.1]: F, [2020-02-26T07:35:04.877614 #4] FATAL -- : [0a72a98b-c5dc-4bac-a68b-420e4a3b6212] ActionView::Template::Error (undefined method `address' for #<Consultation:0x0000000003ad85b0>): 2020-02-26T07:35:04.877882+00:00 app[web.1]: F, [2020-02-26T07:35:04.877825 #4] FATAL -- : [0a72a98b-c5dc-4bac-a68b-420e4a3b6212]     59:   </div> 2020-02-26T07:35:04.877883+00:00 app[web.1]: [0a72a98b-c5dc-4bac-a68b-420e4a3b6212]     60:   <div class="flex-50"> 2020-02-26T07:35:04.877883+00:00 app[web.1]: [0a72a98b-c5dc-4bac-a68b-420e4a3b6212]     61:     <h6><b>Address:</b></h6> 2020-02-26T07:35:04.877884+00:00 app[web.1]: [0a72a98b-c5dc-4bac-a68b-420e4a3b6212]     62:     <p><%= @consultation.address %></p> 2020-02-26T07:35:04.877885+00:00 app[web.1]: [0a72a98b-c5dc-4bac-a68b-420e4a3b6212]     63:   </div> 2020-02-26T07:35:04.877885+00:00 app[web.1]: [0a72a98b-c5dc-4bac-a68b-420e4a3b6212]     64: </div><!--end of flex 4--> 2020-02-26T07:35:04.877886+00:00 app[web.1]: [0a72a98b-c5dc-4bac-a68b-420e4a3b6212]     65: <div> 2020-02-26T07:35:04.877940+00:00 app[web.1]: F, [2020-02-26T07:35:04.877882 #4] FATAL -- : [0a72a98b-c5dc-4bac-a68b-420e4a3b6212] 2020-02-26T07:35:04.878015+00:00 app[web.1]: F, [2020-02-26T07:35:04.877949 #4] FATAL -- : [0a72a98b-c5dc-4bac-a68b-420e4a3b6212] app/views/consultations/_details_consultation_show.html.erb:62:in `_app_views_consultations__details_consultation_show_html_erb__4392516765474927800_70349183947620' 2020-02-26T07:35:04.878015+00:00 app[web.1]: [0a72a98b-c5dc-4bac-a68b-420e4a3b6212] app/views/consultations/show.html.erb:50:in `_app_views_consultations_show_html_erb__2919774553417422322_70349183802880' 2020-02-26T07:35:04.879084+00:00 heroku[router]: at=info method=GET path="/consultations/1" host=eslsearch.herokuapp.com request_id=0a72a98b-c5dc-4bac-a68b-420e4a3b6212 fwd="125.142.66.134" dyno=web.1 connect=0ms service=36ms status=500 bytes=1827 protocol=https 2020-02-26T07:37:57.354246+00:00 heroku[web.1]: Idling 2020-02-26T07:37:57.427564+00:00 heroku[web.1]: State changed from up to down 2020-02-26T07:37:58.539082+00:00 heroku[web.1]: Stopping all processes with SIGTERM 2020-02-26T07:37:58.654255+00:00 heroku[web.1]: Process exited with status 143 2020-02-26T07:37:58.555798+00:00 app[web.1]: - Gracefully stopping, waiting for requests to finish 2020-02-26T07:37:58.567740+00:00 app[web.1]: === puma shutdown: 2020-02-26 07:37:58 +0000 === 2020-02-26T07:37:58.567798+00:00 app[web.1]: - Goodbye! 2020-02-26T07:37:58.568015+00:00 app[web.1]: Exiting revealed  on  and  on  consultation#dashboard to be the source of errors.. The project worked in development; but threw errors on Heroku<br>, this should fix the